
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make fedora'
	@echo
	@echo '	$$ make debian'
	@echo
	@echo '	$$ make ubuntu'
	@echo
	@echo '	$$ make archlinux'
	@echo


.PHONY: help


fedora:
	@./fedora.sh
.PHONY: fedora


debian:
	@./debian.sh
.PHONY: debian


ubuntu:
	@./ubuntu.sh
.PHONY: ubuntu


archlinux:
	@./archlinux.sh
.PHONY: archlinux
